apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-db
  namespace: core
  labels:
    app.kubernetes.io/name: cms-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-db
  template:
    metadata:
      labels:
        app: cms-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "payload"
            - name: POSTGRES_PASSWORD
              value: "payload123"
            - name: POSTGRES_DB
              value: "cms-db"
          resources:
            limits:
              memory: "256Mi"
