apiVersion: apps/v1
kind: StatefulSet # ðŸ‘ˆ MudanÃ§a para StatefulSet
metadata:
  name: cms-db
  namespace: core
  labels:
    app.kubernetes.io/name: cms-db
    app.kubernetes.io/component: database
spec:
  serviceName: "cms-db" # NecessÃ¡rio para StatefulSets
  replicas: 1
  selector:
    matchLabels:
      app: cms-db
  template:
    metadata:
      labels:
        app: cms-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cms-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cms-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "cms-db"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
