apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
stringData:
  # O HOST é 'blog-db', que é o nome do Service que criamos no passo 1
  DATABASE_URI: "postgres://payload:payload123@blog-db:5432/blog-cms-db"
  PAYLOAD_SECRET: "segredo-super-seguro-local"
