apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: curator
resources:
  - ../../base/cms-db # Caminho relativo para a base do DB
  - ../../base/cms-service # Caminho relativo para a base do CMS
  - namespace.yaml
