apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/blog-db # Caminho relativo para a base do DB
  - ../../base/blog-cms # Caminho relativo para a base do CMS
  - blog-secrets.yaml # Arquivo vizinho
