apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-deployment
  namespace: cms
  labels:
    app: curator-cms
spec:
  replicas: 1 # Apenas 1 r√©plica para economizar no MVP
  selector:
    matchLabels:
      app: curator-cms
  template:
    metadata:
      labels:
        app: curator-cms
    spec:
      containers:
        - name: payload-cms
          image: gcr.io/curator-667ef/curator-cms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: cms-secrets
                  key: database-uri
            - name: PAYLOAD_SECRET
              valueFrom:
                secretKeyRef:
                  name: cms-secrets
                  key: payload-secret
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"

          livenessProbe:
            httpGet:
              path: /admin/login
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /admin/login
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
