apiVersion: v1
kind: Secret
stringData:
  DATABASE_URI: "postgres://payload:payload123@blog-db:5432/blog-cms-db"
  PAYLOAD_SECRET: "segredo-super-seguro-local"
  NEXT_PUBLIC_SERVER_URL: "http://cms.curator.local"

  FORCE_DB_SYNC: "true"
  PAYLOAD_DB_PUSH: "true"
  NODE_ENV: "development"
