apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-service
  namespace: core
  labels:
    app.kubernetes.io/name: cms-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-service
  template:
    metadata:
      labels:
        app: cms-service
    spec:
      containers:
        - name: cms-service
          image: docker.io/curator/backend/cms-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: cms-secrets # ðŸ‘ˆ Vai puxar as env vars desse segredo
          env:
            - name: NODE_ENV
              value: "development"
            - name: FORCE_DB_SYNC
              value: "true"
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1Gi"
