apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cms-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Essencial para upload de arquivos no CMS
    nginx.ingress.kubernetes.io/client-body-buffer-size: "1m"
spec:
  rules:
    - host: cms.curator.local
      http:
        paths:
          - path: /
            pathType: Prefix # Melhor para capturar todas as rotas do Next.js
            backend:
              service:
                name: cms-service
                port:
                  number: 3000
