apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: core

# Isso garante que todos os recursos tenham esses labels
labels:
  - pairs:
      app.kubernetes.io/part-of: curator
      env: local

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret.yaml
  - hpa.yaml
