apiVersion: v1
kind: Secret
metadata:
  name: cms-secrets
type: Opaque
stringData:
  # Dados para o CMS
  DATABASE_URI: "postgres://payload:payload123@cms-db:5432/cms-db"
  PAYLOAD_SECRET: "segredo-super-seguro-local"
  NEXT_PUBLIC_SERVER_URL: "http://cms.curator.local"
  NODE_ENV: "development"

  # Dados para o Banco (que o StatefulSet vai ler)
  POSTGRES_USER: "payload"
  POSTGRES_PASSWORD: "payload123"
  POSTGRES_DB: "cms-db"
