name: ğŸš€ CD - Documentation

on:
  push:
    branches: [main]
    paths:
      - apps/frontend/docs/**
      - pnpm-lock.yaml

permissions:
  id-token: write # Required for AWS credential federation
  contents: read # Required to checkout code

jobs:
  deploy:
    name: ğŸ“¦ Build & Deploy Docs
    runs-on: ubuntu-latest

    env:
      TURBO_TEAM: curator
      TURBO_API: s3://curator-turbo-cache?region=us-east-1
      TURBO_CACHE: remote:rw

    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.5.0

      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: pnpm

      - name: ğŸ“¥ Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: ğŸ—ï¸ Build Static Site
        run: pnpm turbo run build --filter=@frontend/docs

      - name: ğŸ”‘ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::735702560853:role/github-deploy-role-docs.curator.com.br
          aws-region: us-east-1

      - name: â˜ï¸ Sync to S3
        run: aws s3 sync ./apps/frontend/docs/out s3://docs.curator.com.br --delete

      - name: ğŸ”„ Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E3FRPQU4BALAJH --paths "/*"
