name: "Deploy Documentation"

on:
  push:
    branches:
      - main
    paths:
      - "apps/frontend/docs/**"
      - "pnpm-lock.yaml"

jobs:
  build-and-deploy-docs:
    name: "Build and Deploy Nextra Docs"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      TURBO_TEAM: "curator"
      TURBO_API: "s3://curator-turbo-cache?region=us-east-1"
      TURBO_REMOTE_ONLY: "true"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v3
        with:
          version: 9.5.0

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: "Install Dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Build Static Site (Turborepo)"
        run: pnpm turbo run build --filter=@frontend/docs

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::735702560853:role/github-deploy-role-docs.curator.com.br
          aws-region: "us-east-1"

      - name: "Sync files to S3"
        run: |
          aws s3 sync ./apps/frontend/docs/out s3://docs.curator.com.br --delete

      - name: "Invalidate CloudFront Cache"
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3FRPQU4BALAJH \
            --paths "/*"
